services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: devmentorhub
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
